"""Generates a Dockerfile + requirements.txt for the pipeline."""
from __future__ import annotations
from app.models.pipeline import PipelineDAG

DOCKERFILE = '''\
# ============================================================
#  Dockerfile — {name}
#  Generated by AI-IDE
# ============================================================
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy pipeline script and any local data files (CSV, Parquet, etc.)
COPY . .

CMD ["python", "pipeline.py"]
'''


def assemble(dag: PipelineDAG, snippets: list[str], packages: list[str]) -> tuple[str, str]:
    dockerfile = DOCKERFILE.format(name=dag.name)
    requirements = "\n".join(packages) + "\n" if packages else ""
    # Return Dockerfile + requirements.txt as a combined string separated by a sentinel
    combined = (
        f"# === Dockerfile ===\n{dockerfile}\n"
        f"# === requirements.txt ===\n{requirements}"
    )
    filename = "Dockerfile"
    return combined, filename
