"""Assembles a Kubeflow Pipelines v2 DSL Python file from ordered node snippets."""
from __future__ import annotations
from app.models.pipeline import PipelineDAG

HEADER = '''\
# ============================================================
#  Kubeflow Pipeline: {name}
#  Generated by AI-IDE
#  Run: python {filename} && kfp run create --experiment-name "{name}" -f pipeline.yaml
# ============================================================
from kfp import dsl
from kfp.compiler import Compiler

'''

PIPELINE_HEADER = '''

@dsl.pipeline(name="{name}", description="AI-IDE generated pipeline")
def pipeline():
'''

FOOTER = '''
if __name__ == "__main__":
    Compiler().compile(pipeline, "pipeline.yaml")
    print("Compiled to pipeline.yaml")
'''


def assemble(dag: PipelineDAG, snippets: list[str], packages: list[str]) -> tuple[str, str]:
    filename = dag.name.lower().replace(" ", "_") + "_kubeflow.py"
    header = HEADER.format(name=dag.name, filename=filename)

    # Wrap each snippet in a kfp component
    component_names: list[str] = []
    components: list[str] = []
    for i, snippet in enumerate(snippets):
        indented = "\n".join(f"    {line}" for line in snippet.splitlines())
        name = f"step_{i + 1}"
        component_names.append(name)
        components.append(
            f"@dsl.component(packages_to_install={packages!r})\n"
            f"def {name}():\n"
            f"{indented}\n"
        )

    # Build the pipeline function body — call each component and chain sequentially
    pipeline_lines: list[str] = []
    for i, name in enumerate(component_names):
        if i == 0:
            pipeline_lines.append(f"    task_{i + 1} = {name}()")
        else:
            pipeline_lines.append(f"    task_{i + 1} = {name}().after(task_{i})")

    pipeline_body = PIPELINE_HEADER.format(name=dag.name)
    pipeline_body += "\n".join(pipeline_lines) + "\n"

    code = header + "\n\n".join(components) + pipeline_body + "\n" + FOOTER
    return code, filename
