"""Assembles a Kubeflow Pipelines v2 DSL Python file from ordered node snippets."""
from __future__ import annotations
from app.models.pipeline import PipelineDAG

HEADER = '''\
# ============================================================
#  Kubeflow Pipeline: {name}
#  Generated by AI-IDE
#  Run: python {filename} && kfp run create --experiment-name "{name}" -f pipeline.yaml
# ============================================================
from kfp import dsl
from kfp.compiler import Compiler

'''

FOOTER = '''

@dsl.pipeline(name="{name}", description="AI-IDE generated pipeline")
def pipeline():
    # TODO: wire component outputs to inputs according to your DAG
    pass


if __name__ == "__main__":
    Compiler().compile(pipeline, "pipeline.yaml")
    print("Compiled to pipeline.yaml")
'''


def assemble(dag: PipelineDAG, snippets: list[str], packages: list[str]) -> tuple[str, str]:
    filename = dag.name.lower().replace(" ", "_") + "_kubeflow.py"
    header = HEADER.format(name=dag.name, filename=filename)
    # Wrap each snippet in a kfp component stub
    components = []
    for i, snippet in enumerate(snippets):
        indented = "\n".join(f"    {line}" for line in snippet.splitlines())
        component_name = f"step_{i + 1}"
        components.append(
            f"@dsl.component(packages_to_install={packages!r})\n"
            f"def {component_name}():\n"
            f"{indented}\n"
        )
    body = "\n\n".join(components)
    footer = FOOTER.format(name=dag.name)
    code = header + body + footer
    return code, filename
