"""Model Card generator — produces HuggingFace-format MODEL_CARD.md from pipeline DAG."""
from __future__ import annotations

from datetime import datetime
from typing import Any


def generate(dag: dict[str, Any]) -> str:
    """Return MODEL_CARD.md content for the given pipeline DAG."""
    name = dag.get("name", "Unnamed Pipeline")
    created = datetime.utcnow().strftime("%Y-%m-%d")
    nodes = dag.get("nodes", [])

    # Collect metadata from node configs by category
    train_nodes  = [n for n in nodes if _cat(n) in ("train", "finetune")]
    eval_nodes   = [n for n in nodes if _cat(n) == "evaluate"]
    ingest_nodes = [n for n in nodes if _cat(n) == "ingest"]
    deploy_nodes = [n for n in nodes if _cat(n) == "deploy"]

    # Build sections
    lines: list[str] = []

    lines += [
        "---",
        f"model_name: {name}",
        f"date: {created}",
        "framework: ConduitCraft AI",
        "tags:",
        "  - conduitcraft",
    ]
    if train_nodes:
        lines.append("  - machine-learning")
    if any(_cat(n) == "llm" for n in nodes):
        lines.append("  - llm")
        lines.append("  - rag")
    lines.append("---")
    lines.append("")
    lines.append(f"# {name}")
    lines.append("")
    lines.append(
        f"> Generated by [ConduitCraft AI](https://github.com/nkamrudeen/conduitcraft-ai) on {created}"
    )
    lines.append("")

    # Model description
    lines.append("## Model Description")
    lines.append("")
    lines.append(
        f"This model was built using a ConduitCraft AI pipeline with {len(nodes)} node(s)."
    )
    lines.append("")

    # Data
    if ingest_nodes:
        lines.append("## Training Data")
        lines.append("")
        for n in ingest_nodes:
            cfg = n.get("config", {})
            did = n.get("definitionId", "")
            if "file_path" in cfg:
                lines.append(f"- **Source**: `{cfg['file_path']}`")
            elif "dataset_name" in cfg:
                lines.append(f"- **HuggingFace Dataset**: `{cfg['dataset_name']}`")
                if cfg.get("split"):
                    lines.append(f"  - Split: `{cfg['split']}`")
            elif "bucket" in cfg:
                lines.append(f"- **S3**: `s3://{cfg['bucket']}/{cfg.get('key', '')}`")
            else:
                lines.append(f"- `{did}`")
        lines.append("")

    # Model architecture
    if train_nodes:
        lines.append("## Model Architecture")
        lines.append("")
        for n in train_nodes:
            cfg = n.get("config", {})
            did = n.get("definitionId", "")
            lines.append(f"### {_label(did)}")
            for k, v in cfg.items():
                if k not in ("tracking_uri", "experiment_name") and v not in ("", None):
                    lines.append(f"- **{k}**: `{v}`")
            lines.append("")

    # Evaluation
    if eval_nodes:
        lines.append("## Evaluation")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        for n in eval_nodes:
            cfg = n.get("config", {})
            did = n.get("definitionId", "")
            lines.append(f"| eval_node | `{_label(did)}` |")
            for k, v in cfg.items():
                if isinstance(v, (int, float)):
                    lines.append(f"| {k} | {v} |")
        lines.append("")

    # Deployment
    if deploy_nodes:
        lines.append("## Deployment")
        lines.append("")
        for n in deploy_nodes:
            cfg = n.get("config", {})
            did = n.get("definitionId", "")
            lines.append(f"- **Method**: `{_label(did)}`")
            if "endpoint_name" in cfg:
                lines.append(f"  - Endpoint: `{cfg['endpoint_name']}`")
            if "model_name" in cfg:
                lines.append(f"  - Model name: `{cfg['model_name']}`")
        lines.append("")

    # All packages
    all_pkgs = sorted({
        p
        for n in nodes
        for p in _pkgs_for(n.get("definitionId", ""))
    })
    if all_pkgs:
        lines.append("## Requirements")
        lines.append("")
        lines.append("```")
        lines += all_pkgs
        lines.append("```")
        lines.append("")

    lines.append("## Citation")
    lines.append("")
    lines.append("```bibtex")
    lines.append("@misc{conduitcraft,")
    lines.append(f"  title  = {{{name}}},")
    lines.append(f"  year   = {{{created[:4]}}},")
    lines.append("  author = {ConduitCraft AI},")
    lines.append("}")
    lines.append("```")

    return "\n".join(lines) + "\n"


def _cat(node: dict[str, Any]) -> str:
    did: str = node.get("definitionId", "")
    parts = did.split(".")
    return parts[1] if len(parts) >= 2 else ""


def _label(did: str) -> str:
    return did.replace(".", " › ").replace("_", " ").title()


_PKG_MAP: dict[str, list[str]] = {
    "ml.train.sklearn": ["scikit-learn"],
    "ml.train.keras": ["tensorflow"],
    "ml.train.pytorch": ["torch"],
    "ml.ingest.csv": ["pandas"],
    "ml.ingest.parquet": ["pandas", "pyarrow"],
    "ml.ingest.huggingface": ["datasets"],
    "ml.evaluate": ["scikit-learn", "matplotlib"],
    "ml.deploy.mlflow": ["mlflow"],
    "llm.model.openai": ["langchain-openai"],
    "llm.model.anthropic": ["langchain-anthropic"],
    "llm.model.ollama": ["langchain-ollama"],
    "llm.chain.rag": ["langchain", "langchain-core"],
    "llm.vectorstore.chroma": ["chromadb", "langchain-chroma"],
    "llm.vectorstore.faiss": ["faiss-cpu", "langchain-community"],
    "llm.embed.openai": ["langchain-openai"],
    "llm.finetune": ["peft", "transformers", "trl"],
}


def _pkgs_for(did: str) -> list[str]:
    for prefix, pkgs in _PKG_MAP.items():
        if did.startswith(prefix):
            return pkgs
    return []
