"""Assembles a Jupyter notebook (.ipynb) from ordered node snippets."""
from __future__ import annotations
import json
from app.models.pipeline import PipelineDAG


def _cell(source: str, cell_type: str = "code") -> dict:
    return {
        "cell_type": cell_type,
        "metadata": {},
        "source": source,
        "outputs": [] if cell_type == "code" else None,
        "execution_count": None if cell_type == "code" else None,
    }


def assemble(dag: PipelineDAG, snippets: list[str], packages: list[str]) -> tuple[str, str]:
    cells = []
    # Title markdown cell
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": f"# {dag.name}\n\nGenerated by **AI-IDE** · Pipeline type: `{dag.pipeline}`",
    })
    # Install cell
    if packages:
        cells.append(_cell(f"!pip install {' '.join(packages)}", "code"))
    # One cell per node snippet
    for snippet in snippets:
        cells.append(_cell(snippet, "code"))

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11.0"},
        },
        "cells": cells,
    }
    code = json.dumps(notebook, indent=2)
    filename = dag.name.lower().replace(" ", "_") + ".ipynb"
    return code, filename
