"""Python package layout generator.

Produces a proper src-layout Python package from the flat pipeline code:

    {project_folder}/
        src/
            {slug}/
                __init__.py        (exposes run())
                pipeline.py        (the full sequential code wrapped in run())
        pipeline.py                (entrypoint: from <slug> import run; run())
        requirements.txt
        pyproject.toml
"""
from __future__ import annotations

import re
import textwrap
from pathlib import Path

from app.models.pipeline import PipelineDAG


def _slug(name: str) -> str:
    """Convert a pipeline name to a valid Python identifier."""
    slug = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    return slug or "pipeline"


def _make_pipeline_module(dag: PipelineDAG, flat_code: str) -> str:
    """Wrap the flat sequential pipeline code in a run() function."""
    # Indent the flat code by 4 spaces to put it inside run()
    indented = textwrap.indent(flat_code.rstrip(), "    ")
    return textwrap.dedent(f"""\
        # ============================================================
        #  Pipeline: {dag.name}
        #  Type:     {dag.pipeline}
        #  Generated by ConduitCraft AI
        # ============================================================
        from __future__ import annotations


        def run() -> None:
            \"\"\"Execute the full pipeline sequentially.\"\"\"
        {indented}


        if __name__ == "__main__":
            run()
    """)


def _make_init(slug: str) -> str:
    return textwrap.dedent(f"""\
        \"\"\"{slug} — generated by ConduitCraft AI.\"\"\"
        from .pipeline import run

        __all__ = ["run"]
    """)


def _make_entrypoint(slug: str, dag: PipelineDAG) -> str:
    return textwrap.dedent(f"""\
        # ============================================================
        #  Pipeline: {dag.name}
        #  Install:  pip install -e .
        #  Run:      python pipeline.py
        # ============================================================
        import sys
        import pathlib

        sys.path.insert(0, str(pathlib.Path(__file__).parent / "src"))

        from {slug} import run

        if __name__ == "__main__":
            run()
    """)


def _make_pyproject(dag: PipelineDAG, slug: str, packages: list[str]) -> str:
    deps = "\n".join(f'  "{p}",' for p in packages)
    return textwrap.dedent(f"""\
        [build-system]
        requires = ["setuptools>=68"]
        build-backend = "setuptools.backends.legacy:build"

        [project]
        name = "{slug}"
        version = "0.1.0"
        description = "Generated pipeline: {dag.name}"
        requires-python = ">=3.10"
        dependencies = [
        {deps}
        ]

        [tool.setuptools.packages.find]
        where = ["src"]
    """)


def write_package(
    dag: PipelineDAG,
    flat_code: str,
    packages: list[str],
    project_folder: str,
) -> list[str]:
    """Write a Python src-layout package structure to *project_folder*.

    Args:
        dag:            The pipeline DAG (for name/type metadata).
        flat_code:      The already-assembled flat pipeline.py code string.
        packages:       List of required pip packages.
        project_folder: Destination directory.

    Returns:
        List of absolute paths for every file written.
    """
    root = Path(project_folder).expanduser().resolve()
    slug = _slug(dag.name)
    pkg_dir = root / "src" / slug
    pkg_dir.mkdir(parents=True, exist_ok=True)

    written: list[str] = []

    # src/<slug>/pipeline.py — sequential code wrapped in run()
    pipeline_mod = pkg_dir / "pipeline.py"
    pipeline_mod.write_text(_make_pipeline_module(dag, flat_code), encoding="utf-8")
    written.append(str(pipeline_mod))

    # src/<slug>/__init__.py
    init_path = pkg_dir / "__init__.py"
    init_path.write_text(_make_init(slug), encoding="utf-8")
    written.append(str(init_path))

    # Root pipeline.py entrypoint
    ep_path = root / "pipeline.py"
    ep_path.write_text(_make_entrypoint(slug, dag), encoding="utf-8")
    written.append(str(ep_path))

    # requirements.txt
    req_path = root / "requirements.txt"
    req_path.write_text("\n".join(packages) + "\n", encoding="utf-8")
    written.append(str(req_path))

    # pyproject.toml
    pp_path = root / "pyproject.toml"
    pp_path.write_text(_make_pyproject(dag, slug, packages), encoding="utf-8")
    written.append(str(pp_path))

    return written
