"""Python package layout generator.

Produces a proper src-layout Python package from ordered node snippets:

    {project_folder}/
        src/
            {slug}/
                __init__.py
                ingest.py
                transform.py
                train.py
                evaluate.py
                deploy.py
                monitor.py
                chunks.py        (LLM)
                embed.py         (LLM)
                vectorstore.py   (LLM)
                llm_models.py    (LLM)
                chain.py         (LLM)
                finetune.py      (LLM)
        pipeline.py              (flat entrypoint — imports from package)
        requirements.txt
        pyproject.toml
"""
from __future__ import annotations

import re
import textwrap
from pathlib import Path

from app.models.pipeline import PipelineDAG

# Maps definitionId prefix → module filename (without .py)
_PREFIX_TO_MODULE: list[tuple[str, str]] = [
    ("ml.ingest.",    "ingest"),
    ("llm.ingest.",   "ingest"),
    ("ml.transform.", "transform"),
    ("ml.train.",     "train"),
    ("ml.evaluate.",  "evaluate"),
    ("ml.deploy.",    "deploy"),
    ("llm.deploy.",   "deploy"),
    ("ml.monitor.",   "monitor"),
    ("ml.mlflow.",    "monitor"),
    ("llm.chunk.",    "chunks"),
    ("llm.embed.",    "embed"),
    ("llm.vectorstore.", "vectorstore"),
    ("llm.model.",    "llm_models"),
    ("llm.chain.",    "chain"),
    ("llm.finetune.", "finetune"),
    ("llm.monitor.",  "monitor"),
]


def _module_for(definition_id: str) -> str:
    for prefix, module in _PREFIX_TO_MODULE:
        if definition_id.startswith(prefix):
            return module
    return "misc"


def _slug(name: str) -> str:
    """Convert a pipeline name to a valid Python identifier."""
    slug = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    return slug or "pipeline"


def _make_init(slug: str, modules: list[str]) -> str:
    imports = "\n".join(f"from .{m} import *  # noqa: F401,F403" for m in sorted(set(modules)))
    return f'"""{slug} — generated by Conduit Studio."""\n{imports}\n'


def _make_pyproject(dag: PipelineDAG, slug: str, packages: list[str]) -> str:
    deps = "\n".join(f'  "{p}",' for p in packages)
    return textwrap.dedent(f"""\
        [build-system]
        requires = ["setuptools>=68"]
        build-backend = "setuptools.backends.legacy:build"

        [project]
        name = "{slug}"
        version = "0.1.0"
        description = "Generated pipeline: {dag.name}"
        requires-python = ">=3.10"
        dependencies = [
        {deps}
        ]

        [tool.setuptools.packages.find]
        where = ["src"]
    """)


def _make_entrypoint(slug: str, modules: list[str], dag: PipelineDAG, packages: list[str]) -> str:
    pkg_str = " ".join(packages) if packages else "# none"
    imports = "\n".join(f"from {slug}.{m} import *  # noqa: F401,F403" for m in sorted(set(modules)))
    return textwrap.dedent(f"""\
        # ============================================================
        #  Pipeline: {dag.name}
        #  Type:     {dag.pipeline}
        #  Generated by Conduit Studio (package layout)
        # ============================================================
        # Install:  pip install -e .
        # Run:      python pipeline.py
        # ============================================================
        import sys, pathlib
        sys.path.insert(0, str(pathlib.Path(__file__).parent / "src"))

        {imports}

        if __name__ == "__main__":
            pass  # All steps run at import time via module-level code above.
    """)


def write_package(
    dag: PipelineDAG,
    ordered_nodes: list,
    snippets: list[str],
    packages: list[str],
    project_folder: str,
) -> list[str]:
    """Write a Python package structure to *project_folder*.

    Returns a list of absolute paths for every file written.
    """
    root = Path(project_folder).expanduser().resolve()
    slug = _slug(dag.name)
    pkg_dir = root / "src" / slug
    pkg_dir.mkdir(parents=True, exist_ok=True)

    # Group snippets by module
    module_snippets: dict[str, list[str]] = {}
    modules_used: list[str] = []
    for node, snippet in zip(ordered_nodes, snippets):
        mod = _module_for(node.definitionId)
        module_snippets.setdefault(mod, []).append(snippet)
        modules_used.append(mod)

    written: list[str] = []

    # Write per-module files
    module_header = (
        "# ── {mod}.py — generated by Conduit Studio ──────────────────────────────\n"
        "from __future__ import annotations\n\n"
    )
    for mod, mod_snippets in module_snippets.items():
        content = module_header.format(mod=mod) + "\n\n".join(mod_snippets)
        out = pkg_dir / f"{mod}.py"
        out.write_text(content, encoding="utf-8")
        written.append(str(out))

    # __init__.py
    init_path = pkg_dir / "__init__.py"
    init_path.write_text(_make_init(slug, list(module_snippets.keys())), encoding="utf-8")
    written.append(str(init_path))

    # pipeline.py entrypoint
    ep_path = root / "pipeline.py"
    ep_path.write_text(
        _make_entrypoint(slug, list(module_snippets.keys()), dag, packages),
        encoding="utf-8",
    )
    written.append(str(ep_path))

    # requirements.txt
    req_path = root / "requirements.txt"
    req_path.write_text("\n".join(packages) + "\n", encoding="utf-8")
    written.append(str(req_path))

    # pyproject.toml
    pp_path = root / "pyproject.toml"
    pp_path.write_text(_make_pyproject(dag, slug, packages), encoding="utf-8")
    written.append(str(pp_path))

    return written
