"""Assembles a standalone Python script from ordered node snippets."""
from __future__ import annotations
from app.models.pipeline import PipelineDAG

HEADER = '''\
# ============================================================
#  Pipeline: {name}
#  Type:     {pipeline}
#  Generated by AI-IDE
# ============================================================
# Install dependencies:
#   pip install {packages}
# ============================================================

'''


def assemble(dag: PipelineDAG, snippets: list[str], packages: list[str]) -> tuple[str, str]:
    pkg_str = " ".join(packages) if packages else "# (no external packages)"
    header = HEADER.format(name=dag.name, pipeline=dag.pipeline, packages=pkg_str)
    body = "\n\n".join(snippets)
    code = header + body + "\n"
    filename = dag.name.lower().replace(" ", "_") + ".py"
    return code, filename
