import type { NodeDefinition } from '@ai-ide/types'

const datasetIn = { id: 'dataset', label: 'Dataset', type: 'DataFrame' } as const
const configIn = { id: 'config', label: 'LoRA Config', type: 'Any' } as const
const modelOut = { id: 'model', label: 'Fine-Tuned Model', type: 'Model' } as const

export const llmFinetuneNodes: NodeDefinition[] = [
  {
    id: 'llm.finetune.dataset_prep',
    category: 'finetune',
    pipeline: 'llm',
    label: 'Dataset Prep',
    description: 'Load and format a dataset into instruction/chat format for fine-tuning',
    icon: '📋',
    color: '#7c3aed',
    inputs: [],
    outputs: [{ id: 'dataset', label: 'Formatted Dataset', type: 'DataFrame' }],
    configSchema: {
      type: 'object',
      required: ['source_type'],
      properties: {
        source_type: {
          type: 'string',
          title: 'Dataset Source',
          enum: ['huggingface', 'csv', 'jsonl'],
          default: 'huggingface',
        },
        dataset_name: { type: 'string', title: 'HuggingFace Dataset Name', default: 'tatsu-lab/alpaca' },
        file_path: { type: 'string', title: 'Local File Path (CSV/JSONL)' },
        format: {
          type: 'string',
          title: 'Prompt Format',
          enum: ['alpaca', 'chatml', 'llama3', 'custom'],
          default: 'alpaca',
        },
        instruction_col: { type: 'string', title: 'Instruction Column', default: 'instruction' },
        input_col: { type: 'string', title: 'Input Column', default: 'input' },
        output_col: { type: 'string', title: 'Output Column', default: 'output' },
        max_samples: { type: 'integer', title: 'Max Samples (0 = all)', default: 0 },
        train_split: { type: 'number', title: 'Train Split Ratio', default: 0.95 },
      },
    },
    codeTemplateId: 'llm/finetune_dataset_prep',
    requiredPackages: ['datasets', 'transformers', 'pandas'],
  },
  {
    id: 'llm.finetune.lora_config',
    category: 'finetune',
    pipeline: 'llm',
    label: 'LoRA Config',
    description: 'Configure Low-Rank Adaptation (LoRA) parameters for efficient fine-tuning',
    icon: '🔧',
    color: '#7c3aed',
    inputs: [],
    outputs: [{ id: 'config', label: 'LoRA Config', type: 'Any' }],
    configSchema: {
      type: 'object',
      required: ['base_model'],
      properties: {
        base_model: { type: 'string', title: 'Base Model (HF repo or path)', default: 'meta-llama/Llama-3.2-1B-Instruct' },
        r: { type: 'integer', title: 'LoRA Rank (r)', default: 16 },
        lora_alpha: { type: 'integer', title: 'LoRA Alpha', default: 32 },
        lora_dropout: { type: 'number', title: 'LoRA Dropout', default: 0.05 },
        target_modules: {
          type: 'array',
          title: 'Target Modules',
          items: { type: 'string' },
          default: ['q_proj', 'v_proj', 'k_proj', 'o_proj'],
        },
        bias: { type: 'string', title: 'Bias', enum: ['none', 'all', 'lora_only'], default: 'none' },
        task_type: { type: 'string', title: 'Task Type', enum: ['CAUSAL_LM', 'SEQ_2_SEQ_LM'], default: 'CAUSAL_LM' },
      },
    },
    codeTemplateId: 'llm/finetune_lora_config',
    requiredPackages: ['peft', 'transformers'],
  },
  {
    id: 'llm.finetune.qlora_config',
    category: 'finetune',
    pipeline: 'llm',
    label: 'QLoRA Config',
    description: 'Configure Quantized LoRA (QLoRA) with 4-bit NF4 quantization via bitsandbytes',
    icon: '⚡',
    color: '#7c3aed',
    inputs: [],
    outputs: [{ id: 'config', label: 'QLoRA Config', type: 'Any' }],
    configSchema: {
      type: 'object',
      required: ['base_model'],
      properties: {
        base_model: { type: 'string', title: 'Base Model (HF repo or path)', default: 'meta-llama/Llama-3.1-8B-Instruct' },
        load_in_4bit: { type: 'boolean', title: 'Load in 4-bit', default: true },
        bnb_4bit_quant_type: {
          type: 'string',
          title: '4-bit Quant Type',
          enum: ['nf4', 'fp4'],
          default: 'nf4',
        },
        bnb_4bit_compute_dtype: {
          type: 'string',
          title: 'Compute dtype',
          enum: ['bfloat16', 'float16', 'float32'],
          default: 'bfloat16',
        },
        use_nested_quant: { type: 'boolean', title: 'Double Quantization', default: true },
        r: { type: 'integer', title: 'LoRA Rank (r)', default: 64 },
        lora_alpha: { type: 'integer', title: 'LoRA Alpha', default: 16 },
        lora_dropout: { type: 'number', title: 'LoRA Dropout', default: 0.1 },
        target_modules: {
          type: 'array',
          title: 'Target Modules',
          items: { type: 'string' },
          default: ['q_proj', 'v_proj', 'k_proj', 'o_proj', 'gate_proj', 'up_proj', 'down_proj'],
        },
      },
    },
    codeTemplateId: 'llm/finetune_qlora_config',
    requiredPackages: ['peft', 'transformers', 'bitsandbytes'],
  },
  {
    id: 'llm.finetune.sft_trainer',
    category: 'finetune',
    pipeline: 'llm',
    label: 'SFT Trainer',
    description: 'Supervised Fine-Tuning with TRL SFTTrainer — supports LoRA, QLoRA, and full fine-tuning',
    icon: '🏋️',
    color: '#7c3aed',
    inputs: [datasetIn, configIn],
    outputs: [modelOut],
    configSchema: {
      type: 'object',
      required: ['output_dir'],
      properties: {
        output_dir: { type: 'string', title: 'Output Directory', default: './fine_tuned_model' },
        num_train_epochs: { type: 'integer', title: 'Training Epochs', default: 3 },
        per_device_train_batch_size: { type: 'integer', title: 'Batch Size per Device', default: 4 },
        gradient_accumulation_steps: { type: 'integer', title: 'Gradient Accumulation Steps', default: 4 },
        learning_rate: { type: 'number', title: 'Learning Rate', default: 0.0002 },
        lr_scheduler_type: {
          type: 'string',
          title: 'LR Scheduler',
          enum: ['cosine', 'linear', 'constant', 'cosine_with_restarts'],
          default: 'cosine',
        },
        warmup_ratio: { type: 'number', title: 'Warmup Ratio', default: 0.03 },
        max_seq_length: { type: 'integer', title: 'Max Sequence Length', default: 2048 },
        logging_steps: { type: 'integer', title: 'Logging Steps', default: 10 },
        save_steps: { type: 'integer', title: 'Save Steps', default: 100 },
        fp16: { type: 'boolean', title: 'FP16 Training', default: false },
        bf16: { type: 'boolean', title: 'BF16 Training', default: true },
        packing: { type: 'boolean', title: 'Sample Packing', default: false },
      },
    },
    codeTemplateId: 'llm/finetune_sft_trainer',
    requiredPackages: ['trl', 'peft', 'transformers', 'accelerate', 'torch'],
  },
  {
    id: 'llm.finetune.merge_push',
    category: 'finetune',
    pipeline: 'llm',
    label: 'Merge & Push',
    description: 'Merge LoRA adapter weights into base model and push to HuggingFace Hub',
    icon: '🚀',
    color: '#7c3aed',
    inputs: [modelOut],
    outputs: [],
    configSchema: {
      type: 'object',
      properties: {
        repo_id: { type: 'string', title: 'HuggingFace Repo ID (user/model-name)' },
        push_to_hub: { type: 'boolean', title: 'Push to HuggingFace Hub', default: true },
        private: { type: 'boolean', title: 'Private Repository', default: false },
        save_merged_local: { type: 'boolean', title: 'Also Save Locally', default: true },
        merged_output_dir: { type: 'string', title: 'Local Merged Model Dir', default: './merged_model' },
        token_env: { type: 'string', title: 'HF Token Env Var', default: 'HF_TOKEN' },
      },
    },
    codeTemplateId: 'llm/finetune_merge_push',
    requiredPackages: ['peft', 'transformers', 'huggingface_hub'],
  },
]
