import type { NodeDefinition } from '@ai-ide/types'

export const llmModelNodes: NodeDefinition[] = [
  {
    id: 'llm.model.openai',
    category: 'llm',
    pipeline: 'llm',
    label: 'OpenAI',
    description: 'OpenAI GPT-4o / GPT-4 / GPT-3.5 models',
    icon: '🤖',
    color: '#10a37f',
    inputs: [{ id: 'vectorstore', label: 'Vector Store (optional)', type: 'VectorStore' }],
    outputs: [{ id: 'llm', label: 'LLM', type: 'Any' }],
    configSchema: {
      type: 'object',
      properties: {
        model: { type: 'string', title: 'Model', enum: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo', 'gpt-3.5-turbo'], default: 'gpt-4o-mini' },
        api_key_env: { type: 'string', title: 'API Key Env Var', default: 'OPENAI_API_KEY' },
        temperature: { type: 'number', title: 'Temperature', default: 0.7, minimum: 0, maximum: 2 },
        max_tokens: { type: 'integer', title: 'Max Tokens', default: 1000 },
        system_prompt: { type: 'string', title: 'System Prompt (optional)' },
      },
    },
    codeTemplateId: 'llm/model_openai',
    requiredPackages: ['langchain-openai'],
    supportsPlayground: true,
  },
  {
    id: 'llm.model.anthropic',
    category: 'llm',
    pipeline: 'llm',
    label: 'Anthropic Claude',
    description: 'Anthropic Claude 3.5 / 3 / Haiku models',
    icon: '🔮',
    color: '#d97706',
    inputs: [{ id: 'vectorstore', label: 'Vector Store (optional)', type: 'VectorStore' }],
    outputs: [{ id: 'llm', label: 'LLM', type: 'Any' }],
    configSchema: {
      type: 'object',
      properties: {
        model: { type: 'string', title: 'Model', enum: ['claude-opus-4-6', 'claude-sonnet-4-6', 'claude-haiku-4-5-20251001'], default: 'claude-sonnet-4-6' },
        api_key_env: { type: 'string', title: 'API Key Env Var', default: 'ANTHROPIC_API_KEY' },
        temperature: { type: 'number', title: 'Temperature', default: 0.7, minimum: 0, maximum: 1 },
        max_tokens: { type: 'integer', title: 'Max Tokens', default: 1000 },
        system_prompt: { type: 'string', title: 'System Prompt (optional)' },
      },
    },
    codeTemplateId: 'llm/model_anthropic',
    requiredPackages: ['langchain-anthropic'],
    supportsPlayground: true,
  },
  {
    id: 'llm.model.ollama',
    category: 'llm',
    pipeline: 'llm',
    label: 'Ollama (Local)',
    description: 'Run open LLMs locally via Ollama — no API key, fully offline (Llama, Mistral, Gemma, Phi, Qwen…)',
    icon: '🦙',
    color: '#6366f1',
    inputs: [{ id: 'vectorstore', label: 'Vector Store (optional)', type: 'VectorStore' }],
    outputs: [{ id: 'llm', label: 'LLM', type: 'Any' }],
    configSchema: {
      type: 'object',
      properties: {
        model: {
          type: 'string',
          title: 'Model Name',
          description: 'Any model pulled with "ollama pull <name>"',
          enum: [
            'llama3.2', 'llama3.2:1b', 'llama3.1', 'llama3.1:8b', 'llama3.1:70b',
            'mistral', 'mistral-nemo', 'mixtral',
            'gemma3', 'gemma3:4b', 'gemma3:12b',
            'phi4', 'phi4-mini', 'phi3',
            'qwen2.5', 'qwen2.5:7b', 'qwen2.5-coder',
            'deepseek-r1', 'deepseek-r1:7b', 'deepseek-r1:14b',
            'codellama', 'nomic-embed-text', 'custom',
          ],
          default: 'llama3.2',
        },
        custom_model: { type: 'string', title: 'Custom Model Name (if "custom" selected)' },
        base_url: { type: 'string', title: 'Ollama Base URL', default: 'http://localhost:11434' },
        temperature: { type: 'number', title: 'Temperature', default: 0.7, minimum: 0, maximum: 2 },
        num_ctx: { type: 'integer', title: 'Context Window (num_ctx)', default: 4096 },
        num_predict: { type: 'integer', title: 'Max Tokens (num_predict)', default: -1, description: '-1 = unlimited' },
        top_p: { type: 'number', title: 'Top P', default: 0.9, minimum: 0, maximum: 1 },
        top_k: { type: 'integer', title: 'Top K', default: 40 },
        repeat_penalty: { type: 'number', title: 'Repeat Penalty', default: 1.1 },
        keep_alive: { type: 'string', title: 'Keep Alive', default: '5m', description: 'How long to keep model in memory (e.g. "5m", "1h", "-1" = forever)' },
        format: { type: 'string', title: 'Response Format', enum: ['', 'json'], default: '', description: 'Set to "json" to force JSON output' },
        system_prompt: { type: 'string', title: 'System Prompt (optional)' },
      },
    },
    codeTemplateId: 'llm/model_ollama',
    requiredPackages: ['langchain-ollama'],
    supportsPlayground: true,
  },
  {
    id: 'llm.model.vllm',
    category: 'llm',
    pipeline: 'llm',
    label: 'vLLM',
    description: 'High-throughput local inference via vLLM server',
    icon: '⚡',
    color: '#7c3aed',
    inputs: [{ id: 'vectorstore', label: 'Vector Store (optional)', type: 'VectorStore' }],
    outputs: [{ id: 'llm', label: 'LLM', type: 'Any' }],
    configSchema: {
      type: 'object',
      required: ['model_name'],
      properties: {
        model_name: { type: 'string', title: 'Model Name', description: 'HuggingFace model ID' },
        base_url: { type: 'string', title: 'vLLM Server URL', default: 'http://localhost:8000/v1' },
        temperature: { type: 'number', title: 'Temperature', default: 0.7 },
        max_tokens: { type: 'integer', title: 'Max Tokens', default: 1000 },
      },
    },
    codeTemplateId: 'llm/model_vllm',
    requiredPackages: ['langchain-openai'],
    supportsPlayground: true,
  },
]
