import type { NodeDefinition } from '@ai-ide/types'

export const llmModelNodes: NodeDefinition[] = [
  {
    id: 'llm.model.openai',
    category: 'llm',
    pipeline: 'llm',
    label: 'OpenAI',
    description: 'OpenAI GPT-4o / GPT-4 / GPT-3.5 models',
    icon: '🤖',
    color: '#10a37f',
    inputs: [{ id: 'vectorstore', label: 'Vector Store (optional)', type: 'VectorStore' }],
    outputs: [{ id: 'llm', label: 'LLM', type: 'Any' }],
    configSchema: {
      type: 'object',
      properties: {
        model: { type: 'string', title: 'Model', enum: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo', 'gpt-3.5-turbo'], default: 'gpt-4o-mini' },
        api_key_env: { type: 'string', title: 'API Key Env Var', default: 'OPENAI_API_KEY' },
        temperature: { type: 'number', title: 'Temperature', default: 0.7, minimum: 0, maximum: 2 },
        max_tokens: { type: 'integer', title: 'Max Tokens', default: 1000 },
        system_prompt: { type: 'string', title: 'System Prompt (optional)' },
      },
    },
    codeTemplateId: 'llm/model_openai',
    requiredPackages: ['langchain-openai'],
  },
  {
    id: 'llm.model.anthropic',
    category: 'llm',
    pipeline: 'llm',
    label: 'Anthropic Claude',
    description: 'Anthropic Claude 3.5 / 3 / Haiku models',
    icon: '🔮',
    color: '#d97706',
    inputs: [{ id: 'vectorstore', label: 'Vector Store (optional)', type: 'VectorStore' }],
    outputs: [{ id: 'llm', label: 'LLM', type: 'Any' }],
    configSchema: {
      type: 'object',
      properties: {
        model: { type: 'string', title: 'Model', enum: ['claude-opus-4-6', 'claude-sonnet-4-6', 'claude-haiku-4-5-20251001'], default: 'claude-sonnet-4-6' },
        api_key_env: { type: 'string', title: 'API Key Env Var', default: 'ANTHROPIC_API_KEY' },
        temperature: { type: 'number', title: 'Temperature', default: 0.7, minimum: 0, maximum: 1 },
        max_tokens: { type: 'integer', title: 'Max Tokens', default: 1000 },
        system_prompt: { type: 'string', title: 'System Prompt (optional)' },
      },
    },
    codeTemplateId: 'llm/model_anthropic',
    requiredPackages: ['langchain-anthropic'],
  },
  {
    id: 'llm.model.ollama',
    category: 'llm',
    pipeline: 'llm',
    label: 'Ollama (Local)',
    description: 'Run open LLMs locally via Ollama (Llama, Mistral, Gemma…)',
    icon: '🦙',
    color: '#6366f1',
    inputs: [{ id: 'vectorstore', label: 'Vector Store (optional)', type: 'VectorStore' }],
    outputs: [{ id: 'llm', label: 'LLM', type: 'Any' }],
    configSchema: {
      type: 'object',
      properties: {
        model: { type: 'string', title: 'Model Name', default: 'llama3.2' },
        base_url: { type: 'string', title: 'Ollama Base URL', default: 'http://localhost:11434' },
        temperature: { type: 'number', title: 'Temperature', default: 0.7, minimum: 0, maximum: 1 },
        system_prompt: { type: 'string', title: 'System Prompt (optional)' },
      },
    },
    codeTemplateId: 'llm/model_ollama',
    requiredPackages: ['langchain-ollama'],
  },
  {
    id: 'llm.model.vllm',
    category: 'llm',
    pipeline: 'llm',
    label: 'vLLM',
    description: 'High-throughput local inference via vLLM server',
    icon: '⚡',
    color: '#7c3aed',
    inputs: [{ id: 'vectorstore', label: 'Vector Store (optional)', type: 'VectorStore' }],
    outputs: [{ id: 'llm', label: 'LLM', type: 'Any' }],
    configSchema: {
      type: 'object',
      required: ['model_name'],
      properties: {
        model_name: { type: 'string', title: 'Model Name', description: 'HuggingFace model ID' },
        base_url: { type: 'string', title: 'vLLM Server URL', default: 'http://localhost:8000/v1' },
        temperature: { type: 'number', title: 'Temperature', default: 0.7 },
        max_tokens: { type: 'integer', title: 'Max Tokens', default: 1000 },
      },
    },
    codeTemplateId: 'llm/model_vllm',
    requiredPackages: ['langchain-openai'],
  },
]
