import type { NodeDefinition } from '@ai-ide/types'

export const mlIngestNodes: NodeDefinition[] = [
  {
    id: 'ml.ingest.csv',
    category: 'ingest',
    pipeline: 'ml',
    label: 'CSV File',
    description: 'Load a CSV file into a DataFrame',
    icon: '📄',
    color: '#0ea5e9',
    inputs: [],
    outputs: [{ id: 'df', label: 'DataFrame', type: 'DataFrame' }],
    configSchema: {
      type: 'object',
      required: ['file_path'],
      properties: {
        file_path: { type: 'string', title: 'File Path', description: 'Path to the CSV file' },
        separator: { type: 'string', title: 'Separator', default: ',' },
        encoding: { type: 'string', title: 'Encoding', default: 'utf-8' },
        header: { type: 'integer', title: 'Header Row', default: 0 },
      },
    },
    codeTemplateId: 'ml/ingest_csv',
    requiredPackages: ['pandas'],
  },
  {
    id: 'ml.ingest.parquet',
    category: 'ingest',
    pipeline: 'ml',
    label: 'Parquet File',
    description: 'Load a Parquet file into a DataFrame',
    icon: '🗜️',
    color: '#0ea5e9',
    inputs: [],
    outputs: [{ id: 'df', label: 'DataFrame', type: 'DataFrame' }],
    configSchema: {
      type: 'object',
      required: ['file_path'],
      properties: {
        file_path: { type: 'string', title: 'File Path' },
        columns: { type: 'array', items: { type: 'string' }, title: 'Columns (optional, empty=all)' },
      },
    },
    codeTemplateId: 'ml/ingest_parquet',
    requiredPackages: ['pandas', 'pyarrow'],
  },
  {
    id: 'ml.ingest.s3',
    category: 'ingest',
    pipeline: 'ml',
    label: 'AWS S3',
    description: 'Load a file from AWS S3 into a DataFrame',
    icon: '☁️',
    color: '#f97316',
    inputs: [],
    outputs: [{ id: 'df', label: 'DataFrame', type: 'DataFrame' }],
    configSchema: {
      type: 'object',
      required: ['bucket', 'key'],
      properties: {
        bucket: { type: 'string', title: 'S3 Bucket' },
        key: { type: 'string', title: 'Object Key (path)' },
        file_format: { type: 'string', title: 'Format', enum: ['csv', 'parquet', 'json'], default: 'csv' },
        aws_region: { type: 'string', title: 'AWS Region', default: 'us-east-1' },
        aws_profile: { type: 'string', title: 'AWS Profile (optional)' },
      },
    },
    codeTemplateId: 'ml/ingest_s3',
    requiredPackages: ['pandas', 'boto3', 's3fs'],
    disabled: true,
  },
  {
    id: 'ml.ingest.azure',
    category: 'ingest',
    pipeline: 'ml',
    label: 'Azure Blob',
    description: 'Load a file from Azure Blob Storage',
    icon: '🔷',
    color: '#0078d4',
    inputs: [],
    outputs: [{ id: 'df', label: 'DataFrame', type: 'DataFrame' }],
    configSchema: {
      type: 'object',
      required: ['container', 'blob_name'],
      properties: {
        container: { type: 'string', title: 'Container Name' },
        blob_name: { type: 'string', title: 'Blob Name' },
        connection_string_env: { type: 'string', title: 'Connection String Env Var', default: 'AZURE_STORAGE_CONNECTION_STRING' },
        file_format: { type: 'string', title: 'Format', enum: ['csv', 'parquet', 'json'], default: 'csv' },
      },
    },
    codeTemplateId: 'ml/ingest_azure',
    requiredPackages: ['pandas', 'azure-storage-blob'],
    disabled: true,
  },
  {
    id: 'ml.ingest.gcs',
    category: 'ingest',
    pipeline: 'ml',
    label: 'Google Cloud Storage',
    description: 'Load a file from GCS into a DataFrame',
    icon: '🌐',
    color: '#4285f4',
    inputs: [],
    outputs: [{ id: 'df', label: 'DataFrame', type: 'DataFrame' }],
    configSchema: {
      type: 'object',
      required: ['bucket', 'blob'],
      properties: {
        bucket: { type: 'string', title: 'Bucket Name' },
        blob: { type: 'string', title: 'Blob Path' },
        project: { type: 'string', title: 'GCP Project ID' },
        file_format: { type: 'string', title: 'Format', enum: ['csv', 'parquet', 'json'], default: 'csv' },
      },
    },
    codeTemplateId: 'ml/ingest_gcs',
    requiredPackages: ['pandas', 'google-cloud-storage', 'gcsfs'],
  },
  {
    id: 'ml.ingest.postgres',
    category: 'ingest',
    pipeline: 'ml',
    label: 'PostgreSQL',
    description: 'Load data from a PostgreSQL table or query',
    icon: '🐘',
    color: '#336791',
    inputs: [],
    outputs: [{ id: 'df', label: 'DataFrame', type: 'DataFrame' }],
    configSchema: {
      type: 'object',
      required: ['connection_string_env', 'query'],
      properties: {
        connection_string_env: { type: 'string', title: 'Connection String Env Var', default: 'POSTGRES_URL' },
        query: { type: 'string', title: 'SQL Query', default: 'SELECT * FROM table_name' },
      },
    },
    codeTemplateId: 'ml/ingest_postgres',
    requiredPackages: ['pandas', 'sqlalchemy', 'psycopg2-binary'],
  },
  {
    id: 'ml.ingest.huggingface',
    category: 'ingest',
    pipeline: 'ml',
    label: 'HuggingFace Dataset',
    description: 'Load a dataset from the HuggingFace Hub',
    icon: '🤗',
    color: '#ff9d00',
    inputs: [],
    outputs: [{ id: 'df', label: 'DataFrame', type: 'DataFrame' }],
    configSchema: {
      type: 'object',
      required: ['dataset_name'],
      properties: {
        dataset_name: { type: 'string', title: 'Dataset Name', description: 'e.g. imdb or glue' },
        subset: { type: 'string', title: 'Subset / Config (optional)' },
        split: { type: 'string', title: 'Split', default: 'train' },
      },
    },
    codeTemplateId: 'ml/ingest_huggingface',
    requiredPackages: ['datasets', 'pandas'],
  },
]
