import type { NodeDefinition } from '@ai-ide/types'

const dfIn = { id: 'df_train', label: 'Train DataFrame', type: 'DataFrame' } as const
const modelOut = { id: 'model', label: 'Trained Model', type: 'Model' } as const

export const mlTrainNodes: NodeDefinition[] = [
  // ── scikit-learn ─────────────────────────────────────────────────────────
  {
    id: 'ml.train.sklearn.random_forest',
    category: 'train',
    pipeline: 'ml',
    label: 'Random Forest',
    description: 'scikit-learn RandomForestClassifier / Regressor',
    icon: '🌲',
    color: '#22c55e',
    inputs: [dfIn],
    outputs: [modelOut],
    configSchema: {
      type: 'object',
      required: ['target_column'],
      properties: {
        target_column: { type: 'string', title: 'Target Column' },
        task: { type: 'string', title: 'Task', enum: ['classification', 'regression'], default: 'classification' },
        n_estimators: { type: 'integer', title: 'Number of Trees', default: 100 },
        max_depth: { type: 'integer', title: 'Max Depth (0=unlimited)', default: 0 },
        random_state: { type: 'integer', title: 'Random State', default: 42 },
      },
    },
    codeTemplateId: 'ml/train_sklearn_random_forest',
    requiredPackages: ['scikit-learn', 'pandas'],
  },
  {
    id: 'ml.train.sklearn.gradient_boosting',
    category: 'train',
    pipeline: 'ml',
    label: 'Gradient Boosting',
    description: 'scikit-learn GradientBoostingClassifier / Regressor',
    icon: '🚀',
    color: '#22c55e',
    inputs: [dfIn],
    outputs: [modelOut],
    configSchema: {
      type: 'object',
      required: ['target_column'],
      properties: {
        target_column: { type: 'string', title: 'Target Column' },
        task: { type: 'string', title: 'Task', enum: ['classification', 'regression'], default: 'classification' },
        n_estimators: { type: 'integer', title: 'Estimators', default: 100 },
        learning_rate: { type: 'number', title: 'Learning Rate', default: 0.1 },
        max_depth: { type: 'integer', title: 'Max Depth', default: 3 },
        random_state: { type: 'integer', title: 'Random State', default: 42 },
      },
    },
    codeTemplateId: 'ml/train_sklearn_gradient_boosting',
    requiredPackages: ['scikit-learn', 'pandas'],
  },
  {
    id: 'ml.train.sklearn.logistic_regression',
    category: 'train',
    pipeline: 'ml',
    label: 'Logistic Regression',
    description: 'scikit-learn LogisticRegression',
    icon: '📈',
    color: '#22c55e',
    inputs: [dfIn],
    outputs: [modelOut],
    configSchema: {
      type: 'object',
      required: ['target_column'],
      properties: {
        target_column: { type: 'string', title: 'Target Column' },
        C: { type: 'number', title: 'Regularization (C)', default: 1.0 },
        max_iter: { type: 'integer', title: 'Max Iterations', default: 1000 },
        solver: { type: 'string', title: 'Solver', enum: ['lbfgs', 'liblinear', 'saga'], default: 'lbfgs' },
      },
    },
    codeTemplateId: 'ml/train_sklearn_logistic_regression',
    requiredPackages: ['scikit-learn', 'pandas'],
  },
  {
    id: 'ml.train.sklearn.svm',
    category: 'train',
    pipeline: 'ml',
    label: 'SVM',
    description: 'scikit-learn Support Vector Machine',
    icon: '⚡',
    color: '#22c55e',
    inputs: [dfIn],
    outputs: [modelOut],
    configSchema: {
      type: 'object',
      required: ['target_column'],
      properties: {
        target_column: { type: 'string', title: 'Target Column' },
        task: { type: 'string', title: 'Task', enum: ['classification', 'regression'], default: 'classification' },
        kernel: { type: 'string', title: 'Kernel', enum: ['rbf', 'linear', 'poly', 'sigmoid'], default: 'rbf' },
        C: { type: 'number', title: 'C', default: 1.0 },
      },
    },
    codeTemplateId: 'ml/train_sklearn_svm',
    requiredPackages: ['scikit-learn', 'pandas'],
  },
  {
    id: 'ml.train.sklearn.xgboost',
    category: 'train',
    pipeline: 'ml',
    label: 'XGBoost',
    description: 'XGBoost classifier / regressor',
    icon: '🎯',
    color: '#22c55e',
    inputs: [dfIn],
    outputs: [modelOut],
    configSchema: {
      type: 'object',
      required: ['target_column'],
      properties: {
        target_column: { type: 'string', title: 'Target Column' },
        task: { type: 'string', title: 'Task', enum: ['classification', 'regression'], default: 'classification' },
        n_estimators: { type: 'integer', title: 'Estimators', default: 100 },
        learning_rate: { type: 'number', title: 'Learning Rate', default: 0.1 },
        max_depth: { type: 'integer', title: 'Max Depth', default: 6 },
        random_state: { type: 'integer', title: 'Random State', default: 42 },
      },
    },
    codeTemplateId: 'ml/train_xgboost',
    requiredPackages: ['xgboost', 'pandas'],
  },
  // ── TensorFlow / Keras ───────────────────────────────────────────────────
  {
    id: 'ml.train.keras.sequential',
    category: 'train',
    pipeline: 'ml',
    label: 'Keras Sequential',
    description: 'TensorFlow/Keras Sequential neural network',
    icon: '🧠',
    color: '#ef4444',
    inputs: [dfIn],
    outputs: [modelOut],
    configSchema: {
      type: 'object',
      required: ['target_column'],
      properties: {
        target_column: { type: 'string', title: 'Target Column' },
        task: { type: 'string', title: 'Task', enum: ['classification', 'regression'], default: 'classification' },
        hidden_layers: {
          type: 'array',
          title: 'Hidden Layers (units per layer)',
          items: { type: 'integer' },
          default: [128, 64],
        },
        activation: { type: 'string', title: 'Activation', enum: ['relu', 'tanh', 'sigmoid'], default: 'relu' },
        dropout_rate: { type: 'number', title: 'Dropout Rate', default: 0.2, minimum: 0, maximum: 0.9 },
        epochs: { type: 'integer', title: 'Epochs', default: 50 },
        batch_size: { type: 'integer', title: 'Batch Size', default: 32 },
        learning_rate: { type: 'number', title: 'Learning Rate', default: 0.001 },
      },
    },
    codeTemplateId: 'ml/train_keras_sequential',
    requiredPackages: ['tensorflow', 'pandas', 'scikit-learn'],
  },
  // ── PyTorch ──────────────────────────────────────────────────────────────
  {
    id: 'ml.train.pytorch.tabular',
    category: 'train',
    pipeline: 'ml',
    label: 'PyTorch Tabular',
    description: 'PyTorch MLP for tabular data',
    icon: '🔥',
    color: '#f97316',
    inputs: [dfIn],
    outputs: [modelOut],
    configSchema: {
      type: 'object',
      required: ['target_column'],
      properties: {
        target_column: { type: 'string', title: 'Target Column' },
        task: { type: 'string', title: 'Task', enum: ['classification', 'regression'], default: 'classification' },
        hidden_layers: {
          type: 'array',
          title: 'Hidden Layers (units per layer)',
          items: { type: 'integer' },
          default: [128, 64],
        },
        epochs: { type: 'integer', title: 'Epochs', default: 50 },
        batch_size: { type: 'integer', title: 'Batch Size', default: 32 },
        learning_rate: { type: 'number', title: 'Learning Rate', default: 0.001 },
        device: { type: 'string', title: 'Device', enum: ['cpu', 'cuda', 'mps'], default: 'cpu' },
      },
    },
    codeTemplateId: 'ml/train_pytorch_tabular',
    requiredPackages: ['torch', 'pandas', 'scikit-learn'],
  },
]
