import type { NodeDefinition } from '@ai-ide/types'

export const mlTransformNodes: NodeDefinition[] = [
  {
    id: 'ml.transform.column_select',
    category: 'extract',
    pipeline: 'ml',
    label: 'Column Selector',
    description: 'Select or drop specific columns',
    icon: '🔎',
    color: '#8b5cf6',
    inputs: [{ id: 'df_in', label: 'DataFrame', type: 'DataFrame' }],
    outputs: [{ id: 'df_out', label: 'DataFrame', type: 'DataFrame' }],
    configSchema: {
      type: 'object',
      properties: {
        columns: { type: 'array', items: { type: 'string' }, title: 'Columns to keep (empty = all)' },
        drop_columns: { type: 'array', items: { type: 'string' }, title: 'Columns to drop' },
      },
    },
    codeTemplateId: 'ml/transform_column_select',
    requiredPackages: ['pandas'],
  },
  {
    id: 'ml.transform.missing_values',
    category: 'filter',
    pipeline: 'ml',
    label: 'Missing Values',
    description: 'Handle missing / null values',
    icon: '🕳️',
    color: '#8b5cf6',
    inputs: [{ id: 'df_in', label: 'DataFrame', type: 'DataFrame' }],
    outputs: [{ id: 'df_out', label: 'DataFrame', type: 'DataFrame' }],
    configSchema: {
      type: 'object',
      properties: {
        strategy: {
          type: 'string',
          title: 'Strategy',
          enum: ['drop_rows', 'drop_cols', 'fill_mean', 'fill_median', 'fill_mode', 'fill_constant'],
          default: 'drop_rows',
        },
        fill_value: { type: 'string', title: 'Fill Value (for fill_constant)' },
        columns: { type: 'array', items: { type: 'string' }, title: 'Apply to columns (empty=all)' },
      },
    },
    codeTemplateId: 'ml/transform_missing_values',
    requiredPackages: ['pandas'],
  },
  {
    id: 'ml.transform.row_filter',
    category: 'filter',
    pipeline: 'ml',
    label: 'Row Filter',
    description: 'Filter rows using a pandas query expression',
    icon: '🔍',
    color: '#8b5cf6',
    inputs: [{ id: 'df_in', label: 'DataFrame', type: 'DataFrame' }],
    outputs: [{ id: 'df_out', label: 'DataFrame', type: 'DataFrame' }],
    configSchema: {
      type: 'object',
      required: ['query'],
      properties: {
        query: { type: 'string', title: 'Filter Query', description: 'e.g. age > 18 and salary < 100000' },
      },
    },
    codeTemplateId: 'ml/transform_row_filter',
    requiredPackages: ['pandas'],
  },
  {
    id: 'ml.transform.scaler',
    category: 'transform',
    pipeline: 'ml',
    label: 'Feature Scaler',
    description: 'Scale numeric features (MinMax, Standard, Robust)',
    icon: '📐',
    color: '#8b5cf6',
    inputs: [{ id: 'df_in', label: 'DataFrame', type: 'DataFrame' }],
    outputs: [{ id: 'df_out', label: 'DataFrame', type: 'DataFrame' }],
    configSchema: {
      type: 'object',
      properties: {
        scaler_type: {
          type: 'string',
          title: 'Scaler',
          enum: ['standard', 'minmax', 'robust', 'maxabs'],
          default: 'standard',
        },
        columns: { type: 'array', items: { type: 'string' }, title: 'Numeric columns to scale (empty=all numeric)' },
      },
    },
    codeTemplateId: 'ml/transform_scaler',
    requiredPackages: ['pandas', 'scikit-learn'],
  },
  {
    id: 'ml.transform.encoder',
    category: 'transform',
    pipeline: 'ml',
    label: 'Category Encoder',
    description: 'Encode categorical columns (Label or One-Hot)',
    icon: '🏷️',
    color: '#8b5cf6',
    inputs: [{ id: 'df_in', label: 'DataFrame', type: 'DataFrame' }],
    outputs: [{ id: 'df_out', label: 'DataFrame', type: 'DataFrame' }],
    configSchema: {
      type: 'object',
      properties: {
        encoding: { type: 'string', title: 'Encoding', enum: ['label', 'onehot', 'ordinal'], default: 'onehot' },
        columns: { type: 'array', items: { type: 'string' }, title: 'Categorical columns' },
        drop_original: { type: 'boolean', title: 'Drop original columns', default: true },
      },
    },
    codeTemplateId: 'ml/transform_encoder',
    requiredPackages: ['pandas', 'scikit-learn'],
  },
  {
    id: 'ml.transform.outlier_remove',
    category: 'filter',
    pipeline: 'ml',
    label: 'Outlier Remover',
    description: 'Remove outliers using IQR or Z-score method',
    icon: '📊',
    color: '#8b5cf6',
    inputs: [{ id: 'df_in', label: 'DataFrame', type: 'DataFrame' }],
    outputs: [{ id: 'df_out', label: 'DataFrame', type: 'DataFrame' }],
    configSchema: {
      type: 'object',
      properties: {
        method: { type: 'string', title: 'Method', enum: ['iqr', 'zscore'], default: 'iqr' },
        threshold: { type: 'number', title: 'Threshold (IQR multiplier or Z score)', default: 1.5 },
        columns: { type: 'array', items: { type: 'string' }, title: 'Columns (empty=all numeric)' },
      },
    },
    codeTemplateId: 'ml/transform_outlier_remove',
    requiredPackages: ['pandas', 'scipy'],
  },
  {
    id: 'ml.transform.train_test_split',
    category: 'split',
    pipeline: 'ml',
    label: 'Train / Test Split',
    description: 'Split DataFrame into train and test sets',
    icon: '✂️',
    color: '#ec4899',
    inputs: [{ id: 'df_in', label: 'DataFrame', type: 'DataFrame' }],
    outputs: [
      { id: 'df_train', label: 'Train DataFrame', type: 'DataFrame' },
      { id: 'df_test', label: 'Test DataFrame', type: 'DataFrame' },
    ],
    configSchema: {
      type: 'object',
      required: ['target_column'],
      properties: {
        target_column: { type: 'string', title: 'Target Column' },
        test_size: { type: 'number', title: 'Test Size', default: 0.2, minimum: 0.05, maximum: 0.5 },
        random_state: { type: 'integer', title: 'Random State', default: 42 },
        stratify: { type: 'boolean', title: 'Stratified Split', default: false },
      },
    },
    codeTemplateId: 'ml/transform_train_test_split',
    requiredPackages: ['pandas', 'scikit-learn'],
  },
]
